### ISSUE TITLE
Error when creating a list of vectors

### ISSUE THREAD

**Issue by andxblack** [generateme/fastmath#16] opened 2022-05-09 02:44 UTC
In testing a function that returns random vectors I came across the following issue, but I'm not sure what's going wrong here.

`(repeat 5 (v/vec2 10 10))` 
> ; Error printing return value (ClassCastException) at fastmath.vector.Vec2/equals (vector.clj:333).
> ; clojure.lang.Symbol cannot be cast to fastmath.vector.Vec2

Doing this with normal Clojure vectors gives the correct result
`(repeat 5 [10 10])`
> ([10 10] [10 10] [10 10] [10 10] [10 10])

**Comment by genmeblog** [comment] 2022-05-09 07:24
Hmmm... I can't reproduce that on my side.

Looks like it's not related to a fastmath, rather how it's used later (do you compare it with a symbol?).

Can you give more context please? 
What version of `fastmath` do you use?
What happens when you assign this to a var and access first element?
Please share full stack trace.


```clojure
(repeat 5 (v/vec2 10 10))
;; => (#vec2 [10.0, 10.0] #vec2 [10.0, 10.0] #vec2 [10.0, 10.0] #vec2 [10.0, 10.0] #vec2 [10.0, 10.0])

(def l (repeat 5 (v/vec2 10 10)))
(first l)
;; => #vec2 [10.0, 10.0]
```

**Comment by andxblack** [comment] 2022-05-10 00:43
I think it is something to do with how the repl is printing the results. I'm evaluating it in vscode using Calva. When I do the same in a terminal repl it works as expected.

I can assign it to a var, but the printing the result gives the same error. Accessing the first element is fine though. 

I'm using version 2.1.5, the full stack trace 
```
; Error printing return value (ClassCastException) at fastmath.vector.Vec2/equals (vector.clj:333).
; clojure.lang.Symbol cannot be cast to fastmath.vector.Vec2
clojure.main/repl (main.clj:442)
clojure.main/repl (main.clj:458)
clojure.main/repl (main.clj:368)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:84)
nrepl.middleware.interruptible-eval/evaluate (interruptible_eval.clj:56)
nrepl.middleware.interruptible-eval/interruptible-eval (interruptible_eval.clj:152)
nrepl.middleware.session/session-exec (session.clj:218)
nrepl.middleware.session/session-exec (session.clj:217)
java.lang.Thread/run (Thread.java:748)
```

**Comment by genmeblog** [comment] 2022-05-10 10:04
I see. Can you upgrade to the newest `fastmath`, ie. `2.1.8` and check again? There was a slight change in how object is compared (the . Maybe this is the reason?

If no I'll dig it further.

**Comment by genmeblog** [comment] 2022-05-10 11:28
I've verified this with VC/Calva:

* Version `2.1.5` indeed throws this error
* Version `2.1.8` doesn't

So looks like this is fixes in newest version.

However I don't know why the code used in `2.1.5` creates this problem in Calva.

**Comment by andxblack** [comment] 2022-05-11 01:05
Thanks!

**Comment by genmeblog** [comment] 2023-04-26 11:57
Fixed.

**Closed by genmeblog** 2023-04-26 11:57 UTC
